server:
  port: 9192
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/gtps
    username: ${MYSQL_USER:jasho}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jashobantapatra@gmail.com
    password: ujje agjl hhbo ieoo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG
